from __future__ import annotations

from mcsu.properties import (
    Properties,
    accept_eula,
    ensure_rcon_settings,
    is_eula_accepted,
)

SAMPLE = """\
# Minecraft server properties
# generated by something
enable-rcon=false
rcon.port=25575
motd=A Minecraft Server
max-players=20
"""


def test_parse_and_get():
    props = Properties.loads(SAMPLE)
    assert props.get("motd") == "A Minecraft Server"
    assert props.get_int("max-players") == 20
    assert props.get_bool("enable-rcon") is False
    assert props.get("nonexistent") is None
    assert "motd" in props
    assert "nope" not in props


def test_set_preserves_comments_and_order():
    props = Properties.loads(SAMPLE)
    props.set("enable-rcon", True)
    props.set("new-key", "value")
    out = props.dumps()
    assert "# Minecraft server properties" in out
    assert "enable-rcon=true" in out
    assert "new-key=value" in out
    # Original ordering of existing keys preserved.
    assert out.index("rcon.port") < out.index("motd")


def test_set_bool_serialization():
    props = Properties()
    props.set("flag", False)
    assert props.get("flag") == "false"


def test_eula(tmp_path):
    assert is_eula_accepted(tmp_path) is False
    accept_eula(tmp_path)
    assert is_eula_accepted(tmp_path) is True
    assert (tmp_path / "eula.txt").read_text().strip().endswith("eula=true")


def test_ensure_rcon_settings(tmp_path):
    (tmp_path / "server.properties").write_text(SAMPLE, encoding="utf-8")
    changed = ensure_rcon_settings(tmp_path, port=25599, password="secret")
    assert changed is True
    props = Properties.load(tmp_path / "server.properties")
    assert props.get_bool("enable-rcon") is True
    assert props.get("rcon.port") == "25599"
    assert props.get("rcon.password") == "secret"
    # Second call with same values is a no-op.
    assert ensure_rcon_settings(tmp_path, port=25599, password="secret") is False


def test_ensure_rcon_creates_file(tmp_path):
    changed = ensure_rcon_settings(tmp_path, port=25575, password="pw")
    assert changed is True
    assert (tmp_path / "server.properties").is_file()
