"""Renders an annotated ``mcsu.toml`` from a :class:`ServerConfig`.

Kept separate from :mod:`mcsu.config` so the (verbose) template text does not
clutter the schema definitions. The output round-trips back through
:func:`mcsu.config.load_config`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mcsu.config import ServerConfig


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    raise TypeError(f"cannot serialize {type(value).__name__} to TOML")


def render_template(config: ServerConfig) -> str:
    c = config
    lines: list[str] = []
    add = lines.append

    add("# mcsu — Minecraft Server Utilities configuration")
    add('# Generated by `mcsu init`. Durations accept values like "1h30m" or "240s".')
    add("# Docs: https://github.com/jxn01/minecraft-server-utilities")
    add("")
    add("[server]")
    add(f"name = {_toml_value(c.name)}              # label used in logs & notifications")
    add(
        f"directory = {_toml_value(c.directory)}             # server working dir, relative to this file"
    )
    add(f"jar = {_toml_value(c.jar)}")
    add(
        f"loader = {_toml_value(c.loader)}          # vanilla|paper|purpur|fabric|forge|neoforge|quilt"
    )
    add(f"mc_version = {_toml_value(c.mc_version)}")
    add(f"stop_timeout = {c.stop_timeout}              # seconds to wait for a graceful stop")
    add(
        f"auto_accept_eula = {_toml_value(c.auto_accept_eula)}      # write eula.txt automatically (you accept the Minecraft EULA)"
    )
    add("")
    add("[java]")
    j = c.java
    path_val = _toml_value(j.path) if j.path else '""'
    add(f"path = {path_val}                  # empty = auto-detect via JAVA_HOME / PATH")
    add(f"min_memory = {_toml_value(j.min_memory)}")
    add(f"max_memory = {_toml_value(j.max_memory)}")
    add(f"extra_flags = {_toml_value(j.extra_flags)}")
    add(f"server_args = {_toml_value(j.server_args)}")
    add("")
    add("[rcon]")
    r = c.rcon
    add(f"enabled = {_toml_value(r.enabled)}")
    add(f"host = {_toml_value(r.host)}")
    add(f"port = {r.port}")
    add(f"password = {_toml_value(r.password)}        # must match server.properties rcon.password")
    add(f"timeout = {r.timeout}")
    add("")
    add("[backup]")
    b = c.backup
    add(f"enabled = {_toml_value(b.enabled)}")
    add(f"directory = {_toml_value(b.directory)}")
    add(f"paths = {_toml_value(b.paths)}")
    add(f"interval = {b.interval}             # seconds between backups")
    add(f"format = {_toml_value(b.format)}           # tar.gz|tar|zip")
    add(f"compression_level = {b.compression_level}")
    add(f"keep = {b.keep}                    # max archives to retain (0 = unlimited)")
    add(
        f"keep_days = {b.keep_days}                # also prune archives older than N days (0 = off)"
    )
    add(
        f"skip_if_no_players = {_toml_value(b.skip_if_no_players)}    # don't back up an idle, unchanged world"
    )
    add(
        f"flush_before_backup = {_toml_value(b.flush_before_backup)}   # save-off/save-all via RCON for a consistent snapshot"
    )
    add("")
    add("[restart]")
    s = c.restart
    add(f"enabled = {_toml_value(s.enabled)}")
    add(f"interval = {s.interval}            # seconds between scheduled restarts (0 = off)")
    add(
        f'daily_times = {_toml_value(s.daily_times)}            # e.g. ["04:00"] for wall-clock restarts'
    )
    add(f"warning_seconds = {_toml_value(s.warning_seconds)}")
    add(f"warning_message = {_toml_value(s.warning_message)}")
    add("")
    add("[watchdog]")
    w = c.watchdog
    add(f"enabled = {_toml_value(w.enabled)}")
    add(f"check_interval = {w.check_interval}")
    add(
        f"max_restarts = {w.max_restarts}            # within restart_window before giving up (0 = unlimited)"
    )
    add(f"restart_window = {w.restart_window}")
    add(f"restart_backoff = {w.restart_backoff}")
    add("")
    add("[notifications]")
    n = c.notifications
    add(f"enabled = {_toml_value(n.enabled)}")
    add(f"discord_webhook = {_toml_value(n.discord_webhook)}")
    add(f"username = {_toml_value(n.username)}")
    add(f"events = {_toml_value(n.events)}")
    add(f"notify_player_join = {_toml_value(n.notify_player_join)}")
    add(f"notify_player_leave = {_toml_value(n.notify_player_leave)}")
    add(f"notify_chat = {_toml_value(n.notify_chat)}")
    add("")
    return "\n".join(lines)
