"""Read and edit ``server.properties`` and ``eula.txt``.

``server.properties`` is a Java ``.properties`` file: ``key=value`` lines with
``#`` comments. This module preserves comments and ordering on round-trip,
which matters because operators keep notes in that file.
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
from typing import cast


class Properties:
    """An order- and comment-preserving view of a ``.properties`` file."""

    def __init__(self) -> None:
        # Stored as a list of (kind, payload). kind in {"kv", "raw"}.
        # "kv" payload is (key, value); "raw" payload is the literal line.
        self._lines: list[tuple[str, object]] = []
        self._index: OrderedDict[str, int] = OrderedDict()

    # -- construction ------------------------------------------------------ #

    @classmethod
    def loads(cls, text: str) -> Properties:
        props = cls()
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith(("#", "!")):
                props._lines.append(("raw", line))
                continue
            if "=" in line:
                key, _, value = line.partition("=")
                key = key.strip()
                props._index[key] = len(props._lines)
                props._lines.append(("kv", (key, value.strip())))
            else:
                props._lines.append(("raw", line))
        return props

    @classmethod
    def load(cls, path: str | Path) -> Properties:
        p = Path(path)
        if not p.is_file():
            return cls()
        return cls.loads(p.read_text(encoding="utf-8"))

    # -- access ------------------------------------------------------------ #

    def get(self, key: str, default: str | None = None) -> str | None:
        idx = self._index.get(key)
        if idx is None:
            return default
        _, payload = self._lines[idx]
        return payload[1]  # type: ignore[index]

    def get_bool(self, key: str, default: bool = False) -> bool:
        value = self.get(key)
        if value is None:
            return default
        return value.strip().lower() in ("true", "1", "yes", "on")

    def get_int(self, key: str, default: int = 0) -> int:
        value = self.get(key)
        if value is None:
            return default
        try:
            return int(value)
        except ValueError:
            return default

    def __contains__(self, key: str) -> bool:
        return key in self._index

    def set(self, key: str, value: object) -> None:
        if isinstance(value, bool):
            value = "true" if value else "false"
        value = str(value)
        idx = self._index.get(key)
        if idx is None:
            self._index[key] = len(self._lines)
            self._lines.append(("kv", (key, value)))
        else:
            self._lines[idx] = ("kv", (key, value))

    def as_dict(self) -> dict[str, str]:
        return {
            payload[0]: payload[1]  # type: ignore[index]
            for kind, payload in self._lines
            if kind == "kv"
        }

    # -- serialization ----------------------------------------------------- #

    def dumps(self) -> str:
        out: list[str] = []
        for kind, payload in self._lines:
            if kind == "raw":
                out.append(str(payload))
            else:
                key, value = cast("tuple[str, str]", payload)
                out.append(f"{key}={value}")
        return "\n".join(out) + "\n"

    def save(self, path: str | Path) -> None:
        Path(path).write_text(self.dumps(), encoding="utf-8")


def accept_eula(server_dir: str | Path) -> Path:
    """Write ``eula=true`` to ``eula.txt`` (the caller accepts the EULA)."""
    path = Path(server_dir) / "eula.txt"
    path.write_text(
        "# Generated by mcsu — by setting this you agree to the Minecraft EULA\n"
        "# https://aka.ms/MinecraftEULA\n"
        "eula=true\n",
        encoding="utf-8",
    )
    return path


def is_eula_accepted(server_dir: str | Path) -> bool:
    path = Path(server_dir) / "eula.txt"
    if not path.is_file():
        return False
    return Properties.load(path).get_bool("eula", False)


def ensure_rcon_settings(
    server_dir: str | Path,
    *,
    port: int,
    password: str,
) -> bool:
    """Enable RCON in ``server.properties`` if not already configured.

    Returns ``True`` if the file was modified. Leaves an existing matching
    configuration untouched so we never churn an operator's file needlessly.
    """
    path = Path(server_dir) / "server.properties"
    props = Properties.load(path)
    changed = False
    desired = {
        "enable-rcon": "true",
        "rcon.port": str(port),
        "rcon.password": password,
    }
    for key, value in desired.items():
        if props.get(key) != value:
            props.set(key, value)
            changed = True
    if changed:
        props.save(path)
    return changed
